### ISSUE TITLE
Описание или скрин проекта

### ISSUE THREAD

**Issue by foshechka** [uenify/musician#1]
Хотелось бы увидеть, что из себя будет представлять работоспособный проект. Надеюсь что-то стоящее. Самое главное побольше функций и хороший плеер. Можно сделать без авторизации? Заблокирован ВК ...

**Comment by superhooman** [comment]
Посмотреть на визуальную составляющую плеера можно [тут](https://vk.com/uenify?w=wall243604906_1077)
А насчет вашего вопроса, то увы, плеер нацелен на работу с Вконтакте. А функционал в нем пока что базовый.
